# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cryptomania' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cryptomania
	pod 'Alamofire', '~> 4.4'

  target 'CryptomaniaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptomaniaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
